package net.msk.csvedit;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.io.InputStream;

/**
 * Diese Klasse öffnet ein Fenster mit Textfeld. Dort steht der Inhalt der
 * Datei help.txt, die im Klassenpfad verfügbar sein muss.
 */
public class CSVHelp extends javax.swing.JDialog
{
    static Logger LOGGER = LogManager.getLogger(CSVHelp.class);
    private String helptext;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea jTextArea1;

    /**
     * Creates new form CSVHelp
     */
    public CSVHelp(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setHelptext();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()
    {//GEN-BEGIN:initComponents
        Buttons = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle(java.util.ResourceBundle.getBundle("csvlang").getString("onlinehelp"));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        okButton.setText(java.util.ResourceBundle.getBundle("csvlang").getString("ok"));
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });

        Buttons.add(okButton);

        getContentPane().add(Buttons, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(640, 380));
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jTextArea1.setLineWrap(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_okButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void setHelptext()
    {
        Class clazz = getClass();
        InputStream is = null;
        try
        {
            is = clazz.getResourceAsStream("help.txt");
            if (is != null)
            {
                StringBuffer sb = new StringBuffer();
                while (true)
                {
                    int c = is.read();
                    if (c == -1) break;
                    sb.append((char) c);
                    // aus aesthetischen Gruenden
                    if ((char) c == '\n') sb.append(' ');
                }
                helptext = sb.toString();
            }
        } catch (IOException e)
        {
            LOGGER.error("help.txt not available");
            helptext = "missing help.txt";
        } finally
        {
            try
            {
                if (is != null) is.close();
            } catch (IOException e)
            {
                LOGGER.debug("help.txt not closed: " + e.toString());
            }
            ;
        }
        jTextArea1.setText(helptext);
    }
    // End of variables declaration//GEN-END:variables
}
