package net.msk.csvedit;

public class EditSubstDialog extends javax.swing.JDialog
{

    private boolean sAll = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField rexpr;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField sexpr;
    private javax.swing.JPanel jPanel3;

    /**
     * Creates new form EditSubstDialog
     */
    public EditSubstDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new EditSubstDialog(new javax.swing.JFrame(), true).show();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rexpr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sexpr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.FlowLayout());

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel5.setText("Suchen");
        jPanel3.add(jLabel5);

        jPanel3.add(rexpr);

        jLabel4.setText("Ersetzen");
        jPanel3.add(jLabel4);

        jPanel3.add(sexpr);

        jButton1.setText("substitue");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1);

        jButton2.setText("substitute All");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton2);

        jPanel3.add(jLabel6);

        getContentPane().add(jPanel3);

        pack();
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // Add your handling code here:
        sAll = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // Add your handling code here:
        sAll = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public String getSearch()
    {
        return rexpr.getText();
    }

    public String getSubst()
    {
        return sexpr.getText();
    }

    public boolean getAll()
    {
        return sAll;
    }
    // End of variables declaration//GEN-END:variables

}
