package net.msk.csvedit;

import gnu.regexp.RE;
import gnu.regexp.REException;

public class TestRegExpr extends javax.swing.JDialog
{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField regexpr;
    private javax.swing.JButton subst;
    private javax.swing.JTextField substexpr;
    private javax.swing.JTextField result;
    private javax.swing.JTextField text;


    /**
     * Creates new form TestRegExpr
     */
    public TestRegExpr(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new TestRegExpr(new javax.swing.JFrame(), true).show();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        text = new javax.swing.JTextField();
        regexpr = new javax.swing.JTextField();
        substexpr = new javax.swing.JTextField();
        subst = new javax.swing.JButton();
        result = new javax.swing.JTextField();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        getContentPane().add(text);

        getContentPane().add(regexpr);

        getContentPane().add(substexpr);

        subst.setText("substitute");
        subst.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                substActionPerformed(evt);
            }
        });

        getContentPane().add(subst);

        getContentPane().add(result);

        pack();
    }//GEN-END:initComponents

    private void substActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_substActionPerformed
    {//GEN-HEADEREND:event_substActionPerformed
        // Add your handling code here:
        try
        {
            RE re = new RE(regexpr.getText());
            result.setText(re.substituteAll(text.getText(), substexpr.getText()));
        } catch (REException e)
        {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_substActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    // End of variables declaration//GEN-END:variables

}
