package net.msk.utils.text;

import com.toedter.calendar.JCalendar;

public class JCalendarChooser extends javax.swing.JDialog
{

    private javax.swing.JButton jButton_ok;
    private javax.swing.JPanel jPanel1;

    /**
     * Creates new form testGUI
     */
    public JCalendarChooser(JCalendar jCalendar)
    {
        jPanel1 = new javax.swing.JPanel();
        java.awt.GridBagConstraints gridBagConstraints;
        jPanel1.setLayout(new java.awt.GridBagLayout());
        jButton_ok = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });


        jPanel1.add(jCalendar, new java.awt.GridBagConstraints());

        jButton_ok.setText("auswählen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jButton_ok, gridBagConstraints);

        jButton_ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_okSaveActionPerformed(evt);
            }
        });

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }

    private void jButton_okSaveActionPerformed(java.awt.event.ActionEvent evt)
    {
        exitForm(null);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
    {
        // System.exit(0);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
